name: MLflow CI Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 pandas numpy scikit-learn matplotlib seaborn dagshub

      - name: Train model
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd Membangun_model
          python modelling_tuning.py

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: Membangun_model/artifacts/

      - name: Commit artifacts
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull --rebase origin main
          git add Membangun_model/artifacts/ || true
          git diff --staged --quiet || git commit -m "Auto: update model artifacts"
          git push

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/Rahmahf074/Eksperimen_SML_RahmaHidayatiFitrah.mlflow
          MLFLOW_TRACKING_USERNAME: Rahmahf074
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          docker build -t rahmahidayatifitrah/diabetes-model:latest -f - . <<'EOF'
          FROM python:3.11-slim
          WORKDIR /app
          RUN pip install mlflow==2.19.0 pandas numpy scikit-learn
          COPY Membangun_model/ /app/
          EXPOSE 5000
          CMD ["python", "modelling_tuning.py"]
          EOF
          docker push rahmahidayatifitrah/diabetes-model:latest
